name: Deployment

on:
  push:
    branches: [main]

jobs:
  hexo-deployment:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai

    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        submodules: false

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install dependencies & Generate static files
      run: |
        node -v
        npm i -g hexo-cli
        npm i
        # Fix nunjucks template syntax issue, or it will cause LaTeX compilation problems
        sed -i 's/{{/{$/g' node_modules/nunjucks/src/lexer.js
        sed -i 's/}}/$}/g' node_modules/nunjucks/src/lexer.js
        git diff --name-only ${{ github.event.before }} ${{ github.sha }} | xargs git checkout ${{ github.sha }} --
        hexo clean
        hexo g

    - name: Deploy to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./public
        keep_files: true

